- cpp/quick_sort.cpp
> Added quick_sort to cpp

- cpp/merge_sort.cpp
- cpp/quick_sort.cpp
Please review the changes. Thanks!
> Added merge_sort to cpp

- c/quick_sort.c
#1 Added a new sorting algorithm.
> quick_sort algorithm #1

- python/CountingSort.py
Counting sort is a sorting technique based on keys between a specific range. It works by counting the number of objects having distinct key values (kind of hashing). Then doing some arithmetic to calculate the position of each object in the output sequence.
> added Counting Sort

- c/stack.c
Added More comments to better understand the algorithm
> Added stack.c

- js/Traversal/traversal.js
> Added Linked List Traversal written in JS

- python/InsertionSort.py
Insertion sort is a simple sorting algorithm that builds the final sorted array (or list) one item at a time. It is much less efficient on large lists than more advanced algorithms such as quicksort, heapsort, or merge sort.
> Added Insertion Sort

- python/reverse_array.py
Algorithm to create a reverser array from a specific one. This data structure algorithm has been validated in hackerhank
> Adding data structure algorithm to create a reverse array

- cpp/trie.cpp
added implementation of trie data structure in cpp which has three operations - insertion, deletion and search in trie.
> Added implementation of Trie in cpp

- java/CountingSort.java
Signed-off-by: Ferry van Zeelst <FGvZeelst@Gmail.com>
> Added Java version of CountingSort (static function)

- cpp/Kadane_Largest Sum in Contiguous Subarray.cpp
Added Kadane's Algorithm to find Largest Sum in Contiguous Subarray.
> KadaneAlgo

- cpp/max_And_Min_Heap_Implementation.cpp
- cpp/trie.cpp
Added implementation of min and max heap. Heap sort is implemented using Max heap.
> Add new algo

- java/Tower_Of_Hanoi.java
Added a Java implementation of Tower of Hanoi.
> Added program of TowerOfHanoi in Java.

- python/Node.py
> node structure

- c/Variance Minimization Algorithm/Variance Minimization.c
> Added Variance Maximization Algorithm In C

- javascript/caesar.js
- javascript/vigenere.js
> Add js caesar and vigenere cipher algorithms

- cpp/Binary_search.rb
- cpp/Knuth_Morris_Pratt_Searching.cpp
Knuth Morris Pratt Searching Algo
Happy Hacktoberfest :100:
> Added KMP algorithm and Ruby folder added with binary search in ruby

- cpp/Kadane_Largest Sum in Contiguous Subarray.cpp
- cpp/bucket_sort.cpp
- cpp/dijkstra.cpp
- java/selection_sort.java
- python/selection_sort.py
> Selection sort python

- python/binary_search.py
Python program for finding an element in given list using binary search technique in O(log n).
> Created binary_search.py

- python/Kadene's Algo.py
Program to find maximum contiguous sum in given list using Kadene's Algorithm in O(n).
> Created Kadene's Algo.py

- python/Primality Testing.py
Program for checking whether given number is a prime or not(Primality Testing) in O(sqrt(n)).
> Created Primality Testing.py

- cpp/Primality Testing.cpp
Program for checking whether given number is a prime or not(Primality Testing) in O(sqrt(n)).
> Created Primality Testing.cpp

- python/Prime Factorisation.py
Program for finding prime factorisation of any number.
> Created Prime Factorisation.py

- cpp/BST_class.cpp
Binary Search Trees class to insert,delete,check & print nodes in c++.
> BST_class.cpp

- MaxPriorityQueue.cpp
Operations on max_priority queue.
> MaxPriorityQueue.cpp

- c/Linked List/reverse c.cpp
> Reversed link list

- c/linkedlist.c
Implemented Linked List with following functions
a. Create a linked list.
b. Insert an element at the start of the linked list.
c. Insert an element at the end of the linked list.
d. Insert an element before an existing element whose information is x in a linked list.
e. Insert an element after an existing element whose information is x in a linked list.
f. Delete the first element of the linked list.
g. Delete the last element of the linked list.
h. Delete the element whose information is x from a linked list.
i. Display the contents of the linked list.
> Created Linkedlist.c

- cpp/SudokoSolver.cpp
> Added sudoku solver code

- c/Linked List/end_inser.cpp
Insertion at end with some more functions
> At end insertion

- python/ABPruning.py
This is reference to #1 and aims to add the Alpha Beta Pruning Implementation of the classical tic tac toe game!
> Added Alpha Beta Pruning Algo to guess next best move in tic tac toe

- cpp/longest_common_subsequence.cpp
Adding c++ code to find Longest common subsequence between two sub-strings using Dynamic programming.
> Adding cpp code for Longest common subsequence

- python/knapsack.py
Adding solution for 0-1 Knapsack Problem in python.
> Adding solution for knapsack problem in python

- kotlin/merge_sort.kt
> Merge sort kotlin added

- cpp/huffmann.cpp
> Huffmann EnCoding

- java/selection_sort.java
- python/Kadane.py
- python/Regression.py
- python/selection_sort.py
> Regression

- cpp/algorithms/gcd.cpp
added algo for finding gcd of two numbers in cpp
> added gcd algo

- javascript/AscendingArray.js
ascending array algorithm Javascript
> ascendingarray.js

- cpp/algorithms/fibonacci.cpp
Added code for fibonacci numbers using dynamic programming in cpp.
> added fibonacci dp code in cpp

- cpp/segmented_bit_sieve_of_Eratosthenes.cpp
fastest implementation till date of the base concept
> added segmented sieve of eratosthenes

- csharp/BubbleSort/BubbleSort.cs
> Adding a Bubble sort in Csharp

- csharp/strings/Palindrome.cs
> Added Palindrome check (C#)

- java/ds/BinaryTree/BT_CountnonLeafNodes.java
- java/ds/BinaryTree/BT_DiaPair.java
- java/ds/BinaryTree/BT_Find.java
- java/ds/BinaryTree/BT_Height.java
- java/ds/BinaryTree/BT_LevelOrder.java
- java/ds/BinaryTree/BT_LevelOrderLineWise.java
- java/ds/BinaryTree/BT_LevelOrderZigZag.java
- java/ds/BinaryTree/BT_MirrorTree.java
- java/ds/BinaryTree/BT_ReverseLevelOrderTraversal.java
- java/ds/BinaryTree/BT_Siblings.java
- java/ds/BinaryTree/BT_SumOfLeafNodes.java
- java/ds/BinaryTree/BT_SumTree.java
- java/ds/BinaryTree/BT_boundaryTraversal.java
- java/ds/BinaryTree/BT_diameter.java
- java/ds/BinaryTree/BT_isBalanced.java
- java/ds/BinaryTree/BT_isIdentical.java
- java/ds/BinaryTree/BT_largestBSTPair.java
- java/ds/BinaryTree/BT_numOfLeafs.java
- java/ds/BinaryTree/BT_sumOfNodes.java
- java/ds/BinaryTree/BT_traversalsIteratively.java
- java/ds/BinaryTree/BT_traversalsRecursively.java
- java/ds/BinaryTree/BinaryTree_Size.java
- java/ds/BinaryTree/SerializeDeserializeofBT.java
Signed-off-by: sjsid9 <sjsid9@gmail.com>
Added Many Codes of Binary Tree I have practiced Over months.;)
> Added a lots of code for BinaryTree

- kotlin/ds/stack.kt
Added implementatIon for a generic stack
> Kotlin stack implementation

- kotlin/ds/queue.kt
Generic implementation of queue added
> Queue kotlin implementation

- c/ds/CDLL/CDLL.c
- c/ds/CDLL/CDLL.cfp
- c/ds/CDLL/CDLL.h
- c/ds/CDLL/main.c
- c/ds/CSLL/CSLL.c
- c/ds/CSLL/CSLL.cfp
- c/ds/CSLL/CSLL.h
- c/ds/CSLL/main.c
- c/ds/DLL/DLL.c
- c/ds/DLL/DLL.cfp
- c/ds/DLL/DLL.h
- c/ds/DLL/main.c
- c/ds/SLL/SLL.c
- c/ds/SLL/SLL.cfp
- c/ds/SLL/SLL.h
- c/ds/SLL/main.c
Folders include implementation of the following linked list types:
- Single
- Double
- Circular Single
- Circular Double
All programs include:
- A functon to create the node for the linked list
- A function to insert the node while keeping the list in sorted order
- A function to delete the node frome the list and free it
- A function to print the list in forward traversal order
- A function to compute the lenght of the list
> Added all types of Linked List implementations in C

- cpp/algorithms/counting_sort.cpp
Counting sort algorithm has been added for C++, it can be used for vectors also after slight modifications.
Counting Sort is a useful sorting mechanism for numbers whose range we are aware of.
It carries out the sorting in O(n) time.
> Added counting sort for cpp

- java/ds/queueUsingLL.java
created a class in java which implements all the necessary functions required in a queue such as enqueue, dequeue, size, isEmpty etc
> implemented queue using Linked List

- csharp/strings/FilterIntegers.cs
#1 
Added algorithm to filter Integers included in strings.
> Added FilteringIntegersFromStrings

- csharp/CodeWarsBasicOperations.cs
A cheeky 8 kyu codewars challenge for your hackin pleasure!
> Added a basic algorithm in C#

- cpp/data_structures/Binary Index Tree.cpp
> added Binary Index Tree

- dart/algorithms/MergeSort.dart
> Added Merge Sort in dart/algorithms

- python/algorithms/breadth_first_search.py
- python/algorithms/topological_sort.py
Implemented the Iterative BFS in Python 3.6 with test cases.
> Implemented BFS and Topological Sort in Python 3.6

- cpp/algorithms/Matrix_chain_multiplication.cpp
- cpp/algorithms/Quick_sort.cpp
MCM implemented using Dynamic Programming and Quick Sort in cpp.
> Matrix chain multiplication(MCM) algo added

- haskell/listIntersect.hs
Intersection here refers to when an element is at the same position and has the same value
> new haskell file that gives the intersection of 2 lists

- README.md
Added a space in the repo README.md
> added a space in the repo README.md

- erlang/algorithms/mergesort.erl
- erlang/algorithms/quicksort.erl
Solutions for quicksort and mergesort writing in Erlang.
> Add quicksort and mergesort in Erlang

- c/ds/8_Reverse_stack.c
> Added Reverse_stack.c File

- python/algorithms/kadane.py
- python/algorithms/shell_sort.py
Shell Sort Algorithm for sorting the arrays.
Closes
https://github.com/kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18/issues/328
> Add shell_sort.py: Adds Shell Sort Algoritms

- cpp/sieve_of_eratosthenes.cpp
Implementation in C++ to print all the primes from 1 to n.
> Sieve of Eratosthenes

- javascript/LinkedList/LinkedList.js
Added basic linked list data structure in Javascript.
> Added Linked List in Javascript 

- python/algorithms/Dynamic Programming - Held & Karp
Added the Held and Karp Dynamic Programing based algorithm applied on the TSP with Python. The algorithm also uses Bitmasking techniques to optimize data structure and processing time.
> Added the Held & Karp algorithme with Bitmasking

- np.cpp
- tre.cpp
Name: Vikas Goswami(https://github.com/con007/)
Place: Lucknow
About: Software Developer
Programming Language: C, C++, Python, HTML, CSS
Email: vikaskv001@gmail.com
> Added np problem program in c++

- cpp/ds/DoublyLinkedList.cpp
The Pull Request resolves Issue #21 
Description:
A doubly linked list in cpp. It has the following functions :
* PushFront(T data)
* PushBack(T data)
* At(int pos)
* InsertAt(int pos, T data)
* DeleteAt(int pos)
* Clear()
> added Doubly linked list in cpp

- java/compare_two_arrays.java
- Changed return type to List object
- Initialize the two iterators in the for loops
> Fixed the code

- cpp/data_structures/Red Black Tree.cpp
This is a basic implementation of RBT covering all the salient features.
> Implementation of Red Black Tree

- java/java_palindrome.java
Fixed the return type to boolean
> Fixed return type

- go/data_structures/linkedList.go
Created linked list in Golang and some driver code in main
> Added linked list in Go

- python/algorithms/fermat_mod.py
> 1 algorithm

- cpp/algorithms/prime_sieve.cpp
Added primesive.cpp to calculate all prime numbers less than n
> Added primesieve.cpp

- ruby/algorithms/binary_search.rb
> Binary search implementation in ruby

- rust/selection_sort.rs
Basic implementation with minor tweaks to simply demonstrate the workflow of Rust a little more vividly while maintaining the accuracy of the algorithm.
> Added an implementation of selection sort algorithm in Rust

- go/ds/stack.go
Add stack implementation in Go that supports Push/Pop/String methods. The Stack element is a simple integer. I also created custom errors for edge cases.
> Add Stack data structure implementation in Go

- go/algorithms/insertion_sort.go
Add insertion sort algorithm in Go. It sorts any sortable type and returns the sorted type. An example of such a struct implementing the sort.Interface interface is also provided in the file.
> Add Insertion Sort algorithm implementation in Go

- cpp/algorithms/least_recently_used.cpp
LRU cache implementation using queue and hash map in c++ using STLs.
> Least recently used cache implementation

- python/algorithms/Warshalls_algorithm.py
added warshall's algorithm in python
> Added Warshall's Algorithm python

- cpp/jump_search.cpp
Addresses issue #285 
Like Binary Search, Jump Search is a searching algorithm for sorted arrays. The basic idea is to check fewer elements (than linear search) by jumping ahead by fixed steps or skipping some elements in place of searching all elements.
`Time Complexity : O(√n)`
`Auxiliary Space : O(1)`
> Added jump search algo in CPP

- cpp/algorithms/Kosaraju_algo_SCC.cpp
Added Kosaraju's double pass algorithm for finding Strongly Connected Components.
> Add Kosaraju's Algorithm for finding SCC

- c/algorithm/Tree Traversal
- cpp/algorithms/Interpolation Search
Kindly review this PR and feel free to suggest changes..
> Tree Traversal Algorithms

- ruby/algorithms/merge_sort.rb
Added the merge sort algorithm in Ruby.
Cheers 🍻
> Add merge sort algorithm in Ruby

- php/Sorting/ascending_array.php
Created a function to sort an array in ascending order
> Add ascending array sort in php

- c/algorithm/iterative merge sort.cpp
fixed user input problem in merge sort C language
> added iterative merge sort with user input

- kotlin/ds/linkedlist.kt
> Add Kotlin LinkedList

- csharp/InsertionSortProgram.cs
Added Insertion sort in C#
Can be found at Data-Structures-And-Algorithms-Hacktoberfest18/csharp/InsertionSortProgram.cs
> Added Insertion sort in C#

- csharp/InsertionSortProgram.cs
- csharp/algorithms/BinarySearch.cs
Added Binary Search Algorithm in C#.
File can be found at csharp/algorithms/BinarySearch.cs.
> Binary search branch

- csharp/strings/ReverseString.cs
> Added string reverse in C#

- java/GreatestCommonDivisor.java
- java/algorithms/FibonnaciDP.java
- java/ds/FloydAlgo.java
- Greatest Common Divisor
- Fibonacci Series using Dynamic Programming
- Floyd's Algorithm
> Additions in Java

- 2018201023_5.cpp
Running Median Program in CPP added
> Running Median CPP

- python/algorithms/RandomNum.py
Added a random number generator, based on the number of characters. If there are any other changes needed please tell me, I am getting used to open source.
> Added Random Number Generator to Algorithims

- python/algorithms/dijikstra.py
Implemented Dijikstra(Shortest path algorithm) in Python.
> Implemented Dijikstra in Python

- c/algorithm/NQueens/NQueens.c
- c/algorithm/NQueens/NQueens.h
- c/algorithm/NQueens/main.c
- c/algorithm/NQueens/make
Algorithm of Backtracking is used to put and verify wether or not a stable solution exists where one does not cross of other.
Signed-off-by: Progyan Bhattacharya <progyanb@acm.org>
> NQueens: Put N number of Quuens in a Chess Board

- cpp/KMP_algorithm.cpp
> KMP_algorithm added

- cpp/algorithms/LongestCommonPrefix.cpp
- cpp/algorithms/ShiftBy2places.cpp
- cpp/algorithms/SudokuBacktracking.cpp
- cpp/algorithms/WorkBoggle.cpp
1. Longest Common Prefix 
2. Shift characters by 2 places.
3. Word boggle problem
4. Sudoku using backtracking.
> Added string and backtracking algorithmic problems.

- cpp/algorithms/ParallelBinarySearch.cpp
> Added Parallel Binary Search Code

- python/algorithms/Prime Factorisation.py
instead of simply listing all integer values, they are now grouped together to improve readability.
> improved visual representation of prime factors

- python/algorithms/heapsort.py
> Added heapsort algorithm in python

- python/algorithms/heap_sort.py
Adds the heap sort algorithm in python as requested on issue #487
> Adds heap sort algorithm

- c/ds/cash1.c
Added cash.c which give minimum coins required for respective change
> added cash.c #1

- haskell/fibonacci.hs
Naive solution for fibonacci in Haskell
> fibonacci haskell

- cpp/freqSort.cpp
- cpp/stack_using_2_queues.cpp
the file is called freqSort.cpp
> added frequency sort algorithm

- c/ds/doublylinkedlist.cpp
program for execution of doubly linked list which takes details of consumers .
> doubly linked list

- go/String/isPalindrome.go
added go version of palindrome string check.
> add go isPalindrome

- cpp/data_structures/stack_using_Array.cpp
Stack with fixed size, that bases on one-dimensional array. It has implemented basic functions.
> Added c++ implementation of Stack using Array.

- java/algorithms/math/LcmOfTwoNumbers.java
to calculate the LCM of two integers
> added LCM of 2 numbers

- java/MergeSort.java
Program to Implement Merge Sort
> Merge Sort Implemented

- c/ds/BinarySearchTree.c
Includes Features of Adding to Tree, Deleting from Tree, Display using inorder, preorder and Postorder
> Implemented Binary Search Tree

- c/ds/BinaryTreeGen.c
Can generate tree from postorder and inorder or preorder and inorder
> Generates Binary Tree from Given Traversal Schemes

- c/ds/Linked List/Header based Circular Linked List.c
Program to implement Header based Circular Linked List
> Header based Circular Linked List

- cpp/algorithms/bellman_ford.cpp
- cpp/algorithms/karat_suba.cpp
> Bellman Ford

- csharp/algorithms/heap.cs
> Add heap sort algorith

- java/ds/doubleEndedLinkedLists.java
Implemented the **Java** code for  **Double Ended Linked Lists**. 
.
.
.
Peace!! ✌️
> Java code for Double Ended Linked Lists

- cpp/multiply using array.cpp
this logic of multiplying two number using array will help us to calculate the factorial of numbers upto 100.
i will be uploading factorial of numbers code using this concept so that we can calculate factorial of number upto 100!
> multiplication of two number using Array!

- Csharp/binaysearch.cs
created binary search in C#
Checkout the [reference: ](https://www.c-sharpcorner.com/blogs/binary-search-implementation-using-c-sharp1)
> binary search in C#

- javascript/algorithms/queue.js
- javascript/algorithms/stack.js
Add more javascript algorithms
> Add Queue and Stack to javascript algorithms.

- cpp/SieveOfAtkin.cpp
added Atkins Sieve for prime Numbers
> Sieve of Atkin

- python/algorithms/heap-sort.py
I have added the heap sort algorithm implemented in python.
> Added Heap-sort

- cpp/algorithms/Heap_sort.cpp
Added the heap sort algorithm in c++ language
> Added heap sorting algorithm

- cpp/algorithms/Count Sort.cpp
> Added Count_Sort Sorting Algorithm in C++

- c/algorithm/RadixSort.c
This implementation of Radix Sort is for strings.
> Implemented Radix Sort in C

- csharp/BubbleSort.cs
- csharp/EuclidsAlgorithm.cs
- csharp/LargestNumber.cs
- csharp/Pangram.cs
- csharp/QuickSort.cs
Added:
- Quick sort
- Bubble sort
- Euclid's algorithm
- Largest number finer
- Pangram checker
> Added five more algorithms in C#

- java/RecursiveSingleLinkedListImpl.java
Recursive SLL using LL interface
> Recursive SLL

- python/algorithms/activitySelection.py
Added activity selection problem(Greedy algorithm )
> Activity selection added

- c/algorithm/CoinChange.c
Its a coin change problem with limited Coins !
Consider that you have only 10,20,30 rs. coin !
> Coin Change Problem

- haskell/splitArray.hs
[String] -> ([String], [String])
> Add haskell algorithm to split an array

- c/ds/Tree/preOrder_binary_tree.c
preorder traversing program in c for a binary tree.
> preOrder traversal in binary tree in c-language

- javascript/algorithms/Kadane.js
Hi Guys,
I added the kadane algorithm in js
I hope is everything well commented and documented, if anything doesn't make sense pls tell me, English is not my main language :)
Hope I can help ^^
> Added Kadane Algorithm in js

- java/algorithms/LexicographicalStringComparel.java
- java/algorithms/StringCountBetween.java
- java/algorithms/StringReplaceCount.java
- java/algorithms/Substring.java
As per guidelines, I added the string algorithm in java language.
>  added string algorithms

- cpp/algorithms/binary_search_.cpp
Issue #285 
Binary search in C++
> Added Binary Search

- depthfirstsearch.cpp
Depth-first search (DFS) is an algorithm for traversing or searching tree or graph data structures. The algorithm starts at the root node (selecting some arbitrary node as the root node in the case of a graph) and explores as far as possible along each branch before backtracking.
Applications of DFS-
-> Detecting cycle in a graph 
-> Topological Sorting
-> Solving puzzles with only one solution, such as mazes
->Finding Strongly Connected Components of a graph
> depthfirstsearch.cpp

- cpp/algorithms/N_queens.cpp
- cpp/algorithms/binary_search_.cpp
Issue #1 
N-queen algorithm in C++
> Adds n-queen algorithm

- c/ds/Linked List/circulardoublyll.c
- c/ds/Linked List/circularll.c
- c/ds/Linked List/doublyll.c
- c/ds/Linked List/headercircularll.c
- c/ds/Linked List/headerdoublycircularll.c
- c/ds/Linked List/headerdoublyll.c
- c/ds/Linked List/headerll.c
- c/ds/Linked List/linkedlist.c
- cpp/algorithms/Quick_sort.cpp
- python/algorithms/Kadane.py
*Linked List
*Header Linked List
*Circular Linked list
*Circular Doubly Linked List
*Header Circular Linked List
*Doubly Linked List
> Added following Programs of Linked List written in C

- c/algorithm/ternary search.c
perform ternary search on a sorted array
> ternary search added

- java/algorithms/LBS.java
Longest Bitonic Subsequence has been added in Java
> added an algo 

- java/algorithms/factorial.java
The code will work if the input is large.
> Added the code which will work for large no.'s

- c/algorithm/shellsort.c
Shell Sort is added in Algorithm in c.
> Adding shellsort

- c/algorithm/ChineseRem.c
- c/algorithm/PrimeSieve.c
- c/algorithm/shellsort.c
- ruby/algorithms/mergesort.rb
Adding Chinese Remainder Algorithm using c.
> Chinese rem

- java/algorithms/math/GcdOfArrayOfInt.java
to calculate the GCD of an array of integers
> added GCD of array of integers

- c/algorithm/Sarques_programs/bubble_sort.c
- c/algorithm/Sarques_programs/circular_linked_list.c
- c/algorithm/Sarques_programs/doubly_linked_list.c
- c/algorithm/Sarques_programs/heap_sort.c
- c/algorithm/Sarques_programs/insertion_sort.c
- c/algorithm/Sarques_programs/linkedlist_2.c
- c/algorithm/Sarques_programs/selection_sort.c
> Some more algorithms and programs added

- python/algorithms/fibonacci_search.py
I have added fibonacci search teachnique based program in python
> Add Python implementation of fibonacci search algorithm

- javascript/AlphaBetaPruning/app.css
- javascript/AlphaBetaPruning/app.js
- javascript/AlphaBetaPruning/index.html
> AlphaBetaPruning

- cpp/algorithms/Dutch_National_Flag.cpp
#487 
Dutch national flag algo added, one of the best sorting algo for arrays with  repeating values.
> Dutch national flag algo

- csharp/Fibonacci.cs
Fibonacci implementation in C#
> Fibonacci implementation in C#

- csharp/GreatestCommonDenominator.cs
Fibonacci implementation in C#
> GCD implementation in C#.

- javascript/algorithms/fibonacci.js
Added three methods to solve fibonacci.
> JavaScript (algorithms): Added Fibonacci

- cpp/algorithms/bfs_directed-graph.cpp
adding BFS algorithm for crossing of graphs
> adding bfs algorithm

- javascript/Utility/isNumberPalindrome.js
Given an integer, write a function that returns true if the given number is palindrome, else false. For example, 12321 is palindrome, but 1451 is not palindrome
> JavaScript (Utility): Is number a palindrome

- cpp/SumTree.c
A SumTree is a Binary Tree where the value of a node is equal to sum of the nodes present in its left subtree and right subtree.
> Check that the given binary tree is a Sum tree.

- go/algorithms/merge_sort.go
I just added the merge_sort in golang language
> Added merge sort in golang

- c/algorithm/subsetsumproblem.c
Subset Sum Problem added in C folder
> New algo add in C folder

- java/algorithms/LinkedListLoopDetection.java
- python/algorithms/LinkedListLoopDetection.py
- python/algorithms/LinkedListLoopDetection_py3.py
This is a loop detection algorithm for linked list based on Floyd Cycle Detection Algorithm. Added some cases for checking correctness of algorithm.
Issue: #1 
Edit: Added loop detection algorithm in python3 as well.
> Added loop detection algorithm in linked list with examples

- csharp/Dijkstra.cs
>  Add Dijkstra Algorithm in C#

- java/algorithms/math/PrimeFactorization.java
to find prime factors of an integer
> added algorithm to find prime factors of an integer

- java/ceaser cipher
Implementation of ceaser cipher
> ceaser cipher

- javascript/Stack/Stack.js
yeah I know this is kind of unnecessary
> JS Stack implementation

- union.cpp
code for union find and path compression
> uniongraph.cpp

- python/algorithms/Rabin-Karp Algorithm.py
Rabin-Karp Algorithm has been added under python folder
> Added Rabin-Karp Algorithm

- cpp/algorithms/Maximum_Matching_Blossom_Algorithm.cpp
> Added blossom algorithm for maximum matching

- csharp/algorithms/fibonacci.cs
Recursive fibonacci implementation in c#
> C# | Added fibonacci.cs

- javascript/Math/smallestCommonMultiple.js
Here is my JavaScript implementation of the Smallest Common Multiple algorithm.
> feat: Add Smallest Common Multiple algorithm in JavaScript

- c/decimalbinary.c
decimal to binary and binary to decimal converter
> decimal to binary and vice versa
